### ISSUE TITLE
可分页列表接口的返回体增加total字段

### ISSUE THREAD

**Issue by aqeja** [fBloc/bloc-server#16]
```js
// 目前结构
{
  status_code: 200,
  status_message: "",
  data: []
}
```

```js
// 希望改为如下结构
{
  status_code: 200,
  status_message: "",
  data: {
    total: 100,
    data: []
  }
}
```

**Comment by pillipanda** [comment]
以下两个接口做了此更改：
1. /api/v1/flow_run_record
2. /api/v1/function_run_record
(目前保持function/flow本身的返回都不变，都直接是返回符合条件的全部列表)

更改后的结构为：
{
  status_code: 200,
  status_message: "",
  data: {
    total: 100,
    items: []
  }
}
